"""empty message

Revision ID: 0d8c144f2bea
Revises: 747bdcf72c67
Create Date: 2021-09-30 03:30:43.925123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8c144f2bea'
down_revision = '747bdcf72c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alerts', ['date_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='unique')
    # ### end Alembic commands ###
