"""empty message

Revision ID: 747bdcf72c67
Revises: f5e3b7986cae
Create Date: 2021-09-30 03:29:31.319479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747bdcf72c67'
down_revision = 'f5e3b7986cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abnormals', sa.Column('msg', sa.String(length=200), nullable=True))
    op.drop_index('timestamp', table_name='abnormals')
    op.create_unique_constraint(None, 'abnormals', ['date_time'])
    op.add_column('snorts', sa.Column('msg', sa.String(length=200), nullable=True))
    op.drop_index('timestamp', table_name='snorts')
    op.create_unique_constraint(None, 'snorts', ['date_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snorts', type_='unique')
    op.create_index('timestamp', 'snorts', ['timestamp'], unique=False)
    op.drop_column('snorts', 'msg')
    op.drop_constraint(None, 'abnormals', type_='unique')
    op.create_index('timestamp', 'abnormals', ['timestamp'], unique=False)
    op.drop_column('abnormals', 'msg')
    # ### end Alembic commands ###
