"""empty message

Revision ID: c1caf86b0db5
Revises: 4c645cf0a11d
Create Date: 2021-09-23 01:55:40.797832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1caf86b0db5'
down_revision = '4c645cf0a11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abnormals', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('protocol_type', sa.String(length=10), nullable=True))
    op.add_column('abnormals', sa.Column('src_bytes', sa.BigInteger(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_bytes', sa.BigInteger(), nullable=True))
    op.add_column('abnormals', sa.Column('land', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('wrong_fragment', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('urgent', sa.BigInteger(), nullable=True))
    op.add_column('abnormals', sa.Column('hot', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('srv_count', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('serror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('srv_serror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('rerror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('srv_rerror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('same_srv_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('diff_srv_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('srv_diff_host_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_count', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_srv_count', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_same_srv_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_diff_srv_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_same_src_port_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_srv_diff_host_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_serror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_srv_serror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_rerror_rate', sa.Integer(), nullable=True))
    op.add_column('abnormals', sa.Column('dst_host_srv_rerror_rate', sa.Integer(), nullable=True))
    op.drop_column('abnormals', 'protocol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abnormals', sa.Column('protocol', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('abnormals', 'dst_host_srv_rerror_rate')
    op.drop_column('abnormals', 'dst_host_rerror_rate')
    op.drop_column('abnormals', 'dst_host_srv_serror_rate')
    op.drop_column('abnormals', 'dst_host_serror_rate')
    op.drop_column('abnormals', 'dst_host_srv_diff_host_rate')
    op.drop_column('abnormals', 'dst_host_same_src_port_rate')
    op.drop_column('abnormals', 'dst_host_diff_srv_rate')
    op.drop_column('abnormals', 'dst_host_same_srv_rate')
    op.drop_column('abnormals', 'dst_host_srv_count')
    op.drop_column('abnormals', 'dst_host_count')
    op.drop_column('abnormals', 'srv_diff_host_rate')
    op.drop_column('abnormals', 'diff_srv_rate')
    op.drop_column('abnormals', 'same_srv_rate')
    op.drop_column('abnormals', 'srv_rerror_rate')
    op.drop_column('abnormals', 'rerror_rate')
    op.drop_column('abnormals', 'srv_serror_rate')
    op.drop_column('abnormals', 'serror_rate')
    op.drop_column('abnormals', 'srv_count')
    op.drop_column('abnormals', 'count')
    op.drop_column('abnormals', 'hot')
    op.drop_column('abnormals', 'urgent')
    op.drop_column('abnormals', 'wrong_fragment')
    op.drop_column('abnormals', 'land')
    op.drop_column('abnormals', 'dst_bytes')
    op.drop_column('abnormals', 'src_bytes')
    op.drop_column('abnormals', 'protocol_type')
    op.drop_column('abnormals', 'duration')
    # ### end Alembic commands ###
