"""empty message

Revision ID: feb4febf7fec
Revises: a034db63bb3c
Create Date: 2021-09-30 02:40:42.715207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4febf7fec'
down_revision = 'a034db63bb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abnormals', sa.Column('msg', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'alerts', ['timestamp'])
    op.add_column('snorts', sa.Column('msg', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snorts', 'msg')
    op.drop_constraint(None, 'alerts', type_='unique')
    op.drop_column('abnormals', 'msg')
    # ### end Alembic commands ###
